### ISSUE TITLE
HU 003 - Valor de una hora de parqueo

### ISSUE THREAD

**Issue by MasterHarold** [MasterHarold/gestiondeclientes#3]
**Como cliente, quiero saber cuánto me cuesta una hora de parqueo.**

**Resultado esperado**	Se le dará la opción al cliente la opción de cotizar el valor por el tiempo aproximado que usará el parqueadero.

**Prioridad:** Media

**Criterios de aceptación.**

El sistema contará con un DEMO que hará las simulaciones de ingreso al parqueadero.

El demo no afectará la cuenta de los servicios ya realizados.

**Notas QA** 

Se realiza la prueba de rendimiento de la aplicación, para verificar que si calcule el valor por el tiempo de servicio.

**Requisitos no funcionales.**

**Seguridad:* La aplicación debe denegar el acceso a personal no autorizado. Solamente debe validar el usuario del administrador (a).

**Actuación:** La aplicación solo aceptará dos usuarios de dominios para mayor seguridad y accesibilidad sin ningún percance y contratiempo al iniciar sesión.

**Disponibilidad:** La aplicación se podrá ejecutar en todo momento, las 24 horas del día.

**Mantenimiento:** La aplicación debe estar disponible para atender cualquier tipo de actualización y/o modificación requeridas.

**Portabilidad:** La aplicación solo podrá ser ejecutada en equipo de computo seleccionado, para poder ser ejecutado en otro equipo diferente, debe contar con los permisos de la empresa.

**Fiabilidad:** La aplicación debe garantizar la confianza del administrados y trabajar sin ningún percance o contratiempo

**Usabilidad:** La aplicación debe ser de fácil uso y entendimientos para el administrador.

**Notas UX.**
Este botón de consulta le permitirá al administrador informarle al cliente la cotización que este requiera.
El cliente decidirá si toma o deja el servicio dependiendo el precio del mismo.
Si toma el servicio el vehículo ingresa al parqueadero y si le cobrara según el tiempo que estuvo dentro.

**Scopus > en qué dispositivos y qué OS se van a realizar las pruebas.**

Teniendo en cuenta que es una aplicación para ser ejecutada en dispositivos móviles, podrá ser usada en los siguientes sistemas operativos: Android iOS Symbian Windows IPhone.

**Persona responsable de su desarrollo.**
	
Gustavo López
Francisco Avila

**Comment by Andres-lop** [comment]
He aquí la importancia de los medios utilizados para tener presente el costo del servicio de una manera oportuna y correcta.
